codecov: 
  token: ff487339-77b1-487d-b785-f3bc8a12fc16
  branch: main
name: Bruteforce for subdomains
on: [push, pull_request]
jobs:
  run:
    runs-on: kali-linux
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up Python 3.10
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - name: Install dependencies
        run: python3 setup.py install
      - name: Brute Force for Subdomains
        uses: codecov/codecov-action@v4.0.1
        with:
          flags: smart-tests
          verbose: true
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
          slug: Mr0Wido/bff-subdomains
